build_spider_one_trial <- function(trial){
# This function uses coordinate tables of one arena trial (generated by DLTdv5) to calculate metrics of arm waves.
waves.all <- numeric()

file.points <- paste0("exemplars/", trial, "_xyzpts.csv")
file.CI <- paste0("exemplars/", trial, "_xyzCI.csv")
file.StaEnd <- paste0("exemplars/", trial, "_StartEnd.xlsx")
  
# load data files and create frames holding coordinates of left and right waves ----
trial.data <-
  read.csv(
    file.points,
    header = TRUE,
    stringsAsFactors = FALSE
  )

trial.CI <-
  read.csv(
    file.CI,
    header = TRUE,
    stringsAsFactors = FALSE
  )

start.end.frames <- read_excel(path = file.StaEnd)
start.end.frames[is.na(start.end.frames)] <- 0

# clean up DLT xyz and CI files by adding frame numbers and removing empty rows
trial.data$frame<- 1:nrow(trial.data)
trial.data<- na.omit(trial.data)

trial.CI$frame<- 1:nrow(trial.CI)
trial.CI<- na.omit(trial.CI)

# clean up start/end file by omitting irrelevant columns and renaming the kept ones
start.end.frames <- start.end.frames[, 2:4]
colnames(start.end.frames) <- c("frame", "left", "right")

# join xyz table with start/end frames
trial.data <- inner_join(start.end.frames, trial.data, by = "frame")

# add frame rate column
trial.data$fps <- 120

# deal with "end/start" values by duplicating those rows
trial.data <- split_endStart(trial.data)

# split waves into separate data frames for left and right for ease of use

waves.sides <- split.sides(trial.data)
lefts <- data.frame(waves.sides[1])
rights <- data.frame(waves.sides[2])

# test if there are start/end frames missing---------------------------------------------

if(sum(lefts$event == "start") != sum(lefts$event == "end")) {
  print("left MISMATCH")
} else {
  print("left match")
}

if (sum(rights$event == "start") != sum(rights$event == "end")) {
  print("right MISMATCH")
} else {
  print("right match")
}

if(length(setdiff(start.end.frames$frame, trial.data$frame)) > 0) {
  print(sprintf(
    "Missing data for frame(s) %s.",
    paste0(
      setdiff(start.end.frames$frame, trial.data$frame),
      collapse = ", "
    )
  ))
}

# check for suspicious points
if(any(trial.CI[, 1:36] > 1)) {
  message(sprintf("suspicious point(s): %s.", paste0(which(trial.CI[, 1:36] > 1), collapse = ", ")))
} # FIX right now finds returns cell indices instead of frames that fit condition

# calculate frame with one row per wave----------------------------------------------
waves <- build.waves(lefts, rights)

# export to file
write.csv(waves, file = paste0("exemplars/", trial, "_waves.csv"))
}
# clear workspace
#rm(list = ls())