# This script uses raw coordinate tables of all  arena trials (generated by 
# DLTdv5) to calculate arm wave metrics of each trial and summary statistics 
# for different conditions. The script calls build_spider_fun.R for several
# helper functions.

# load wrangling packages
library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(rgl)
library(readr)
source("R/build_spider_fun.R")

raw_data.all <- numeric()
waves.all <- numeric()

# Point script at raw data----
trials <- dir("Data")

# specify trials with 24 or 30 fps video -----
trials24 <- c("1854 0x","1854 white","1856 0x","1863 0x","1863 white",
              "1864 white","1864 0x","1866 white","1895 0x","1895 white",
              "1927 white", "1929 0x","1929 white","1939 0x","1927 0x",
              "1939 white","1946 0x","1946 white","1947 0x","1967 0x",
              "1984 0x","1974 white","1974 0x","1927 1x","1988 white",
              "1988 0x")

trials30 <- c("1864 1.5x","1867 1x")



# loop through all trials-----

for(i in 1:length(trials)){
  
trial.curr <- trials[i]

## identify xyz points, start/end, and CI tables
file.points <-
  list.files(paste0("Data/", trial.curr), pattern = "_xyzpts.csv")     
file.StaEnd <-
  list.files(paste0("Data/", trial.curr), pattern = "_StartEnd.xlsx")  
file.CI <-
  list.files(paste0("Data/", trial.curr), pattern = "_xyzCI.csv")          

file.points <- paste0("Data/", trial.curr,"/",file.points)  # assemble file path
file.StaEnd <- paste0("Data/", trial.curr,"/",file.StaEnd)
file.CI <- paste0("Data/", trial.curr,"/",file.CI)

## load data files and make frames holding coordinates of left and right waves
trial.data <-
  read.csv(
    file.points,
    header = TRUE,
    stringsAsFactors = FALSE
  )

trial.CI <-
  read.csv(
    file.CI,
    header = TRUE,
    stringsAsFactors = FALSE
  )

start.end.frames <- read_excel(path = file.StaEnd)
start.end.frames[is.na(start.end.frames)] <- 0 # change NAs to zeros

# clean up DLT xyz and CI files by adding frame numbers and removing empty rows
trial.data$frame <- 1:nrow(trial.data)
trial.data <- na.omit(trial.data)

trial.CI$frame <- 1:nrow(trial.CI)
trial.CI <- na.omit(trial.CI)

# clean up start/end file by omitting irrelevant columns and renaming the rest
start.end.frames <- start.end.frames[, 2:4]
colnames(start.end.frames) <- c("frame", "left", "right")

# join xyz table with start/end frames
trial.data <- inner_join(start.end.frames, trial.data, by = "frame")

# add frame rate column
if(trial.curr %in% trials24) {
  trial.data$fps <- 24
} else if (trial.curr %in% trials30) {
  trial.data$fps <- 30
} else {
  trial.data$fps <- 120
}

## add rotated points to trial.data
trial.data <- create_rotated_view(trial.data)

## deal with "end/start" values by duplicating those rows
trial.data <- split_endStart(trial.data)

## split waves into separate data frames for left and right 
waves.sides <- split.sides(trial.data)
lefts <- data.frame(waves.sides[1])
rights <- data.frame(waves.sides[2])

## test if there are start/end frames missing-----------------------------------

if(sum(lefts$event == "start") != sum(lefts$event == "end")) {
  print(sprintf(
    "%s: left MISMATCH, missing data for frame(s) %s.",
    trial.curr,
    paste0(
      setdiff(start.end.frames$frame, trial.data$frame),
      collapse = ", "
    )
  ))
} else {
  print(sprintf("%s: left match", trial.curr))
}

if (sum(rights$event == "start") != sum(rights$event == "end")) {
  print(sprintf(
    "%s: right MISMATCH, missing data for frame(s) %s.",
    trial.curr,
    paste0(
      setdiff(start.end.frames$frame, trial.data$frame),
      collapse = ", "
    )
  ))
} else {
  print(sprintf("%s: right match", trial.curr))
}

# check for suspicious points
if(any(trial.CI[, 1:36] > 1)) {
  message(sprintf(
    "%s: suspicious point(s): %s.",
    trial.curr,
    paste0(which(trial.CI[, 1:36] > 1), collapse = ", ")
  ))
}

## calculate frame with one row per wave----------------------------------------
waves <- build.waves(lefts, rights)

## build master dataframes
trial.data$id <- str_sub(trial.curr, 1, 4)
trial.data$treat <- str_sub(trial.curr, 6, -1)

raw_data.all <- rbind(raw_data.all, trial.data)
waves.all <- rbind(waves.all, waves)

}

# export to file
write.csv(waves.all, file = "waves.csv")
